services:
  db:
    image: postgres:18
    container_name: ask_rabbi_db
    environment:
      POSTGRES_DB: ask_rabbi
      POSTGRES_USER: admin
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2_data.sql
    restart: always

  pgadmin:
      image: dpage/pgadmin4
      container_name: ask_rabbi_admin
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
        PGADMIN_CONFIG_SERVER_MODE: 'False'  
      ports:
        - "${PGADMIN_PORT}:80"
      volumes:
          - ./servers.json:/pgadmin4/servers.json
      depends_on:
        - db
      restart: always
